# Конфигурация плагина The X-Files

# Настройки плагина
settings:
  # Авто-сохранение каждые 10 минут
  auto-save: 600
  # Максимальный уровень доступа
  max-access-level: 10

# Архивы X-Files
archives:
  ufo_sightings:
    name: "Отчеты о наблюдениях НЛО"
    description: "Засекреченные отчеты о наблюдениях неопознанных летающих объектов"
    level: 3
    files:
      - "Отчет Розуэлл 1947"
      - "Случай в Фениксе 1997"
      - "Документы по проекту 'Синяя книга'"
  
  alien_autopsy:
    name: "Вскрытие пришельцев"
    description: "Медицинские отчеты и результаты вскрытий инопланетных существ"
    level: 5
    files:
      - "Вскрытие Розуэллского пришельца"
      - "Биологические образцы внеземного происхождения"
      - "Анализ ДНК инопланетных существ"

# Лаборатории исследований
laboratories:
  genetic_lab:
    name: "Генетическая лаборатория"
    description: "Исследования инопланетной ДНК и гибридизации"
    level: 4
    research:
      - "Гибридные организмы человека и пришельца"
      - "Анализ внеземных патогенов"
      - "Генетические модификации"

  tech_analysis:
    name: "Лаборатория анализа технологий"
    description: "Исследование инопланетных технологий и артефактов"
    level: 6
    research:
      - "Анализ антигравитационных систем"
      - "Исследование внеземных сплавов"
      - "Тестирование энергетического оружия"
